apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot-dec6-3
  janus-idp.io/tekton: chatbot-dec6-3
  backstage.io/kubernetes-id: chatbot-dec6-3
  backstage.io/kubernetes-namespace: chatbot-dec6-3 
  app.kubernetes.io/part-of: chatbot-dec6-3
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
