kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chatbot-dec6-3-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: chatbot-dec6-3-dsp-job
    namespace: chatbot-dec6-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chatbot-dec6-3-imagestream-job-role
